eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port=8761


# Zipkin server URL
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans


# Sampling rate: 1.0 = 100% of requests traced (use lower in prod, e.g. 0.1)
management.tracing.sampling.probability=1.0

logging.level.io.micrometer=DEBUG
logging.level.zipkin2=DEBUG

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
