spring.application.name=order-service

#eureka
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ordersdb
spring.datasource.username=postgres
spring.datasource.password=0000

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

#Manages services heath, usually acompanhante de
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Resilience 4J properties
# Circuit breaker instance named "myServiceCB"
resilience4j.circuitbreaker.instances.inventory.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventory.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.inventory.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.inventory.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventory.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventory.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.inventory.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.inventory.automaticTransitionFromOpenToHalfOpenEnabled=true

#Resilience 4J timeout properties
#resilience4j.timelimiter.instances.inventory.timeout-duration=3s

#Resilience  4j retry Properties
#resilience4j.retry.instances.inventory.max-attempts=5
#resilience4j.retry.instances.inventory.wait-duration=5s

# Zipkin server URL
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Sampling rate: 1.0 = 100% of requests traced (use lower in prod, e.g. 0.1)
management.tracing.sampling.probability=1.0

logging.level.io.micrometer=DEBUG
logging.level.zipkin2=DEBUG

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]


